import {
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";

// Domain tables per docs/PLAN.md §"Database schema" (handoff §13 with amendments).
// better-auth's own tables live in auth-schema.ts (generated by @better-auth/cli).

export const appUsers = pgTable("app_users", {
  id: uuid("id").primaryKey().defaultRandom(),
  // Links to better-auth's user table by email (better-auth user IDs are text).
  email: text("email").notNull().unique(),
  displayName: text("display_name"),
  defaultTimezone: text("default_timezone").notNull().default("America/Chicago"),
  googleHealthUserId: text("google_health_user_id").unique(),
  legacyFitbitUserId: text("legacy_fitbit_user_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const oauthConnections = pgTable(
  "oauth_connections",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => appUsers.id, { onDelete: "cascade" }),
    provider: text("provider").notNull().default("google_health"),
    scopes: text("scopes").array().notNull().default([]),
    // active | reauth_required | revoked
    status: text("status").notNull().default("active"),
    connectedAt: timestamp("connected_at", { withTimezone: true }).notNull().defaultNow(),
    reauthRequiredAt: timestamp("reauth_required_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [unique().on(t.userId, t.provider)],
);

export const oauthTokens = pgTable("oauth_tokens", {
  id: uuid("id").primaryKey().defaultRandom(),
  // Exactly one token row per connection (enables upserts + the refresh lock).
  connectionId: uuid("connection_id")
    .notNull()
    .unique()
    .references(() => oauthConnections.id, { onDelete: "cascade" }),
  accessTokenCiphertext: text("access_token_ciphertext"),
  accessTokenIv: text("access_token_iv"),
  accessTokenTag: text("access_token_tag"),
  accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
  refreshTokenCiphertext: text("refresh_token_ciphertext"),
  refreshTokenIv: text("refresh_token_iv"),
  refreshTokenTag: text("refresh_token_tag"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
  tokenType: text("token_type"),
  keyVersion: integer("key_version").notNull().default(1),
  // Best-effort single-flight refresh lock (neon-http has no interactive
  // transactions): claimant sets now()+30s; a stale/expired lock is claimable.
  // Google does not rotate refresh tokens, so a rare double-refresh is benign.
  refreshInFlightUntil: timestamp("refresh_in_flight_until", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const oauthStates = pgTable("oauth_states", {
  id: uuid("id").primaryKey().defaultRandom(),
  stateHash: text("state_hash").notNull().unique(),
  intendedUserId: uuid("intended_user_id").references(() => appUsers.id, {
    onDelete: "cascade",
  }),
  redirectAfter: text("redirect_after"),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  consumedAt: timestamp("consumed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const mutationAuditLog = pgTable("mutation_audit_log", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").references(() => appUsers.id, { onDelete: "set null" }),
  toolName: text("tool_name").notNull(),
  dataType: text("data_type").notNull(),
  // create | update | delete
  operation: text("operation").notNull(),
  requestPayload: jsonb("request_payload").notNull(),
  responsePayload: jsonb("response_payload"),
  googleDataPointName: text("google_data_point_name"),
  // success | error
  status: text("status").notNull(),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// Dormant until v1.1 (webhooks) — schema present from day one by design.
export const webhookEvents = pgTable(
  "webhook_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    eventHash: text("event_hash").notNull().unique(),
    healthUserId: text("health_user_id").notNull(),
    userId: uuid("user_id").references(() => appUsers.id, { onDelete: "set null" }),
    dataType: text("data_type").notNull(),
    // UPSERT | DELETE
    operation: text("operation").notNull(),
    intervals: jsonb("intervals").notNull().default([]),
    payload: jsonb("payload").notNull(),
    receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow(),
    processedAt: timestamp("processed_at", { withTimezone: true }),
    status: text("status").notNull().default("received"),
  },
  (t) => [index("webhook_events_user_data_type_idx").on(t.healthUserId, t.dataType)],
);

// Dormant until v1.1 — latest webhook notification per (user, data type).
// Webhook payloads carry NO health values, only pointers; this is a freshness
// ledger, not a value store.
export const dataFreshness = pgTable(
  "data_freshness",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => appUsers.id, { onDelete: "cascade" }),
    dataType: text("data_type").notNull(),
    lastNotifiedAt: timestamp("last_notified_at", { withTimezone: true }),
    lastOperation: text("last_operation"),
    lastInterval: jsonb("last_interval"),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [unique().on(t.userId, t.dataType)],
);

// v1 usage is narrow by design: profile/settings/identity/data-type catalog
// only (TTL ~1h). Health data reads are always live in v1.
export const healthCache = pgTable(
  "health_cache",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => appUsers.id, { onDelete: "cascade" }),
    cacheKey: text("cache_key").notNull(),
    dataType: text("data_type"),
    rangeStart: timestamp("range_start", { withTimezone: true }),
    rangeEnd: timestamp("range_end", { withTimezone: true }),
    payload: jsonb("payload").notNull(),
    latestDataTime: timestamp("latest_data_time", { withTimezone: true }),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [unique().on(t.userId, t.cacheKey)],
);
