import {
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";

// Domain tables per docs/PLAN.md §"Database schema" (handoff §13 with amendments).
// better-auth's own tables live in auth-schema.ts (generated by @better-auth/cli).

export const appUsers = pgTable("app_users", {
  id: uuid("id").primaryKey().defaultRandom(),
  // Links to better-auth's user table by email (better-auth user IDs are text).
  email: text("email").notNull().unique(),
  displayName: text("display_name"),
  defaultTimezone: text("default_timezone").notNull().default("America/Chicago"),
  googleHealthUserId: text("google_health_user_id").unique(),
  legacyFitbitUserId: text("legacy_fitbit_user_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const oauthConnections = pgTable(
  "oauth_connections",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => appUsers.id, { onDelete: "cascade" }),
    provider: text("provider").notNull().default("google_health"),
    scopes: text("scopes").array().notNull().default([]),
    // active | reauth_required | revoked
    status: text("status").notNull().default("active"),
    // Monotonic generation for optimistic concurrency between refresh and a
    // reconnect that atomically replaces the Google credential + DPoP key.
    credentialVersion: integer("credential_version").notNull().default(1),
    connectedAt: timestamp("connected_at", { withTimezone: true }).notNull().defaultNow(),
    reauthRequiredAt: timestamp("reauth_required_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [unique().on(t.userId, t.provider)],
);

export const oauthTokens = pgTable("oauth_tokens", {
  id: uuid("id").primaryKey().defaultRandom(),
  // Exactly one token row per connection (enables upserts + the refresh lock).
  connectionId: uuid("connection_id")
    .notNull()
    .unique()
    .references(() => oauthConnections.id, { onDelete: "cascade" }),
  accessTokenCiphertext: text("access_token_ciphertext"),
  accessTokenIv: text("access_token_iv"),
  accessTokenTag: text("access_token_tag"),
  accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
  refreshTokenCiphertext: text("refresh_token_ciphertext"),
  refreshTokenIv: text("refresh_token_iv"),
  refreshTokenTag: text("refresh_token_tag"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
  tokenType: text("token_type"),
  keyVersion: integer("key_version").notNull().default(1),
  // Copy the credential generation onto the row that refresh UPDATEs lock.
  // PostgreSQL EvalPlanQual can then recheck it after a concurrent reconnect.
  credentialVersion: integer("credential_version").notNull().default(1),
  dpopThumbprint: text("dpop_thumbprint"),
  // Single-flight refresh lock (neon-http has no interactive transactions):
  // claimant sets a short deadline and contenders may proceed only after an
  // atomic reacquire. DPoP nonce state makes concurrent refresh unsafe.
  refreshInFlightUntil: timestamp("refresh_in_flight_until", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// One P-256 DPoP key per Google Health connection. The private JWK uses a
// purpose-derived AES-256-GCM key and authenticated connection-id context;
// only the public JWK, thumbprint, and Google-issued nonce are plaintext.
export const googleHealthDpopKey = pgTable("google_health_dpop_key", {
  id: uuid("id").primaryKey().defaultRandom(),
  connectionId: uuid("connection_id")
    .notNull()
    .unique()
    .references(() => oauthConnections.id, { onDelete: "cascade" }),
  privateJwkCiphertext: text("private_jwk_ciphertext").notNull(),
  privateJwkIv: text("private_jwk_iv").notNull(),
  privateJwkTag: text("private_jwk_tag").notNull(),
  keyVersion: integer("key_version").notNull().default(1),
  credentialVersion: integer("credential_version").notNull().default(1),
  publicJwk: jsonb("public_jwk").notNull(),
  thumbprint: text("thumbprint").notNull(),
  nonce: text("nonce"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const oauthStates = pgTable("oauth_states", {
  id: uuid("id").primaryKey().defaultRandom(),
  stateHash: text("state_hash").notNull().unique(),
  intendedUserId: uuid("intended_user_id").references(() => appUsers.id, {
    onDelete: "cascade",
  }),
  redirectAfter: text("redirect_after"),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  consumedAt: timestamp("consumed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const mutationAuditLog = pgTable("mutation_audit_log", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").references(() => appUsers.id, { onDelete: "set null" }),
  toolName: text("tool_name").notNull(),
  dataType: text("data_type").notNull(),
  // create | update | delete
  operation: text("operation").notNull(),
  requestPayload: jsonb("request_payload").notNull(),
  responsePayload: jsonb("response_payload"),
  googleDataPointName: text("google_data_point_name"),
  // success | error
  status: text("status").notNull(),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// Dormant until v1.1 (webhooks) — schema present from day one by design.
export const webhookEvents = pgTable(
  "webhook_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    eventHash: text("event_hash").notNull().unique(),
    healthUserId: text("health_user_id").notNull(),
    userId: uuid("user_id").references(() => appUsers.id, { onDelete: "set null" }),
    dataType: text("data_type").notNull(),
    // UPSERT | DELETE
    operation: text("operation").notNull(),
    intervals: jsonb("intervals").notNull().default([]),
    payload: jsonb("payload").notNull(),
    receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow(),
    processedAt: timestamp("processed_at", { withTimezone: true }),
    status: text("status").notNull().default("received"),
  },
  (t) => [index("webhook_events_user_data_type_idx").on(t.healthUserId, t.dataType)],
);

// Dormant until v1.1 — latest webhook notification per (user, data type).
// Webhook payloads carry NO health values, only pointers; this is a freshness
// ledger, not a value store.
export const dataFreshness = pgTable(
  "data_freshness",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => appUsers.id, { onDelete: "cascade" }),
    dataType: text("data_type").notNull(),
    lastNotifiedAt: timestamp("last_notified_at", { withTimezone: true }),
    lastOperation: text("last_operation"),
    lastInterval: jsonb("last_interval"),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [unique().on(t.userId, t.dataType)],
);

// v1 usage is narrow by design: profile/settings/identity/data-type catalog
// only (TTL ~1h). Health data reads are always live in v1.
export const healthCache = pgTable(
  "health_cache",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => appUsers.id, { onDelete: "cascade" }),
    cacheKey: text("cache_key").notNull(),
    dataType: text("data_type"),
    operation: text("operation").notNull().default("read"),
    rangeStart: timestamp("range_start", { withTimezone: true }),
    rangeEnd: timestamp("range_end", { withTimezone: true }),
    // Deprecated compatibility column. v1.1 clears existing short-lived rows
    // and never writes plaintext here; keep nullable for one release so the
    // migration is additive/non-interactive, then drop it in a later cleanup.
    payload: jsonb("payload"),
    // Nullable for one rolling-deploy bridge: the prior production runtime
    // can still write plaintext-only rows between migration and deployment.
    // v0.2.0 never writes such rows and deletes them on sight.
    payloadCiphertext: text("payload_ciphertext"),
    payloadIv: text("payload_iv"),
    payloadTag: text("payload_tag"),
    keyVersion: integer("key_version").notNull().default(1),
    latestDataTime: timestamp("latest_data_time", { withTimezone: true }),
    sourceFetchedAt: timestamp("source_fetched_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [unique().on(t.userId, t.cacheKey)],
);

// MCP-readable proactive update inbox. Rows contain notification pointers and
// lifecycle state only; health values remain in the encrypted short-lived
// cache and are fetched/shaped when a client reads the update.
export const healthUpdateInbox = pgTable(
  "health_update_inbox",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => appUsers.id, { onDelete: "cascade" }),
    eventHash: text("event_hash").notNull(),
    dataType: text("data_type").notNull(),
    operation: text("operation").notNull(),
    intervals: jsonb("intervals").notNull().default([]),
    status: text("status").notNull().default("pending"),
    notifiedAt: timestamp("notified_at", { withTimezone: true }).notNull().defaultNow(),
    acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    unique().on(t.userId, t.eventHash),
    index("health_update_inbox_user_status_idx").on(t.userId, t.status),
  ],
);
